name: Build deps image

on:
  push:
    paths:
      - "scripts/build_deps.sh"
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bogusscopus
          password: ${{ secrets.DOCKER }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/manylinux_deps.Dockerfile
          push: true
          tags: bogusscopus/manylinux-deps:latest
